/**
 * HITL (Human-in-the-Loop) API — list, approve, and reject pending tool-call
 * approvals generated by running pipelines.
 *
 * Maps to `/api/v1/private/hitl/*`.
 *
 * @example
 * ```ts
 * const pending = await melaya.hitl.pending();
 * for (const req of pending) {
 *   await melaya.hitl.approve(req.requestId, { comment: "Looks good" });
 * }
 * ```
 */
import type { HttpClient } from "./client.js";
import type {
  HitlApproval,
  HitlApprovalHistory,
  HitlBulkDecideBody,
  HitlBulkDecideResult,
  HitlDecideParams,
  RunMessage,
  RunToolCall,
  RunToolStats,
} from "./platform-types.js";

export class HitlAPI {
  constructor(private readonly http: HttpClient) {}

  /** List all pending HITL tool-call approvals for the authenticated user. */
  async pending(): Promise<HitlApproval[]> {
    return this.http.get<HitlApproval[]>("/api/v1/private/hitl/approvals/pending");
  }

  /** List historical (decided) HITL approval records. */
  async history(params?: { limit?: number; offset?: number }): Promise<HitlApprovalHistory[]> {
    return this.http.get<HitlApprovalHistory[]>("/api/v1/private/hitl/approvals/history", {
      ...(params as Record<string, string | number | undefined | null>),
    });
  }

  /** Approve a pending HITL tool-call approval. */
  async approve(requestId: string, params?: HitlDecideParams): Promise<{ ok: boolean }> {
    return this.http.post<{ ok: boolean }>(
      `/api/v1/private/hitl/approvals/${encodeURIComponent(requestId)}/approve`,
      params,
    );
  }

  /** Reject a pending HITL tool-call approval. */
  async reject(requestId: string, params?: HitlDecideParams): Promise<{ ok: boolean }> {
    return this.http.post<{ ok: boolean }>(
      `/api/v1/private/hitl/approvals/${encodeURIComponent(requestId)}/reject`,
      params,
    );
  }

  /**
   * Bulk approve or reject multiple pending approvals in one call.
   *
   * @example
   * ```ts
   * await melaya.hitl.bulkDecide({ requestIds: ["r1", "r2"], decision: "approved" });
   * ```
   */
  async bulkDecide(body: HitlBulkDecideBody): Promise<HitlBulkDecideResult> {
    return this.http.post<HitlBulkDecideResult>("/api/v1/private/hitl/approvals/bulk", body);
  }

  // ── Run-level inspection ─────────────────────────────────────────────────────

  /** Get tool-call statistics for a specific pipeline run. */
  async runToolStats(runId: string): Promise<RunToolStats> {
    return this.http.get<RunToolStats>(
      `/api/v1/private/hitl/runs/${encodeURIComponent(runId)}/tool-stats`,
    );
  }

  /** Get tool-call stats broken down by agent for a run. */
  async runToolStatsByAgent(runId: string): Promise<Record<string, unknown>> {
    return this.http.get<Record<string, unknown>>(
      `/api/v1/private/hitl/runs/${encodeURIComponent(runId)}/tool-stats/by-agent`,
    );
  }

  /** Get paginated messages for a pipeline run. */
  async runMessages(
    runId: string,
    params?: { limit?: number; cursor?: string },
  ): Promise<RunMessage[]> {
    return this.http.get<RunMessage[]>(
      `/api/v1/private/runs/${encodeURIComponent(runId)}/messages`,
      { ...(params as Record<string, string | number | undefined | null>) },
    );
  }

  /** Get all tool calls for a pipeline run. */
  async runToolCalls(runId: string): Promise<RunToolCall[]> {
    return this.http.get<RunToolCall[]>(
      `/api/v1/private/hitl/runs/${encodeURIComponent(runId)}/tool-calls`,
    );
  }
}
