# frozen_string_literal: true

module Melaya
  # HITL (Human-in-the-Loop) API — list, approve, and reject pending
  # tool-call approval requests generated by running agent pipelines.
  #
  # Maps to /api/v1/private/hitl/*.
  #
  # @example
  #   pending = melaya.hitl.pending
  #   pending.each do |req|
  #     melaya.hitl.approve(req["requestId"], comment: "Looks good")
  #   end
  #
  #   # Bulk operations
  #   melaya.hitl.bulk_decide(
  #     request_ids: ["r1", "r2"],
  #     decision: "approved",
  #     comment: "Batch OK"
  #   )
  class HitlAPI
    def initialize(http)
      @http = http
    end

    # GET /api/v1/private/hitl/approvals/pending
    # List all pending HITL tool-call approvals for the authenticated user.
    def pending
      @http.get("/api/v1/private/hitl/approvals/pending")
    end

    # GET /api/v1/private/hitl/approvals/history
    # List historical (decided) HITL approval records.
    # @param limit [Integer, nil]
    # @param offset [Integer, nil]
    def history(limit: nil, offset: nil)
      @http.get("/api/v1/private/hitl/approvals/history",
        compact("limit" => limit, "offset" => offset))
    end

    # POST /api/v1/private/hitl/approvals/:requestId/approve
    # Approve a pending HITL tool-call approval.
    # @param request_id [String]
    # @param comment [String, nil]
    def approve(request_id, comment: nil)
      body = compact("comment" => comment)
      @http.post("/api/v1/private/hitl/approvals/#{enc(request_id)}/approve",
        body.empty? ? nil : body)
    end

    # POST /api/v1/private/hitl/approvals/:requestId/reject
    # Reject a pending HITL tool-call approval.
    # @param request_id [String]
    # @param comment [String, nil]
    def reject(request_id, comment: nil)
      body = compact("comment" => comment)
      @http.post("/api/v1/private/hitl/approvals/#{enc(request_id)}/reject",
        body.empty? ? nil : body)
    end

    # POST /api/v1/private/hitl/approvals/bulk
    # Bulk approve or reject multiple pending tool calls in one call.
    # @param request_ids [Array<String>]
    # @param decision [String] "approved" or "rejected"
    # @param comment [String, nil]
    def bulk_decide(request_ids:, decision:, comment: nil)
      body = compact(
        "requestIds" => request_ids,
        "decision"   => decision,
        "comment"    => comment
      )
      @http.post("/api/v1/private/hitl/approvals/bulk", body)
    end

    # ── Run-level inspection ───────────────────────────────────────────────────

    # GET /api/v1/private/hitl/runs/:runId/tool-stats
    # Get tool-call statistics for a specific pipeline run.
    def run_tool_stats(run_id)
      @http.get("/api/v1/private/hitl/runs/#{enc(run_id)}/tool-stats")
    end

    # GET /api/v1/private/hitl/runs/:runId/tool-stats/by-agent
    # Get tool-call stats broken down by agent for a run.
    def run_tool_stats_by_agent(run_id)
      @http.get("/api/v1/private/hitl/runs/#{enc(run_id)}/tool-stats/by-agent")
    end

    # GET /api/v1/private/hitl/runs/:runId/messages
    # Get paginated messages for a pipeline run.
    # @param limit [Integer, nil]
    # @param cursor [String, nil]
    def run_messages(run_id, limit: nil, cursor: nil)
      @http.get("/api/v1/private/hitl/runs/#{enc(run_id)}/messages",
        compact("limit" => limit, "cursor" => cursor))
    end

    # GET /api/v1/private/hitl/runs/:runId/tool-calls
    # Get all tool calls for a pipeline run.
    def run_tool_calls(run_id)
      @http.get("/api/v1/private/hitl/runs/#{enc(run_id)}/tool-calls")
    end

    private

    def enc(s)
      URI.encode_www_form_component(s.to_s)
    end

    def compact(hash)
      hash.reject { |_, v| v.nil? }
    end
  end
end
