<?php

declare(strict_types=1);

namespace Melaya;

/**
 * HITL (Human-in-the-Loop) API — list, approve, and reject pending tool-call
 * approvals generated by running pipelines.
 *
 * Maps to /api/v1/private/hitl/*.
 *
 * @example
 * ```php
 * $sdk = new Melaya\Melaya(apiKey: getenv('MK'));
 *
 * $pending = $sdk->hitl->pending();
 * foreach ($pending as $req) {
 *     $sdk->hitl->approve($req['requestId'], ['comment' => 'Looks good']);
 * }
 *
 * // Or bulk-approve
 * $sdk->hitl->bulkDecide([
 *     'requestIds' => ['r1', 'r2'],
 *     'decision'   => 'approved',
 * ]);
 * ```
 */
class HitlAPI
{
    public function __construct(private readonly HttpClient $http) {}

    /** List all pending HITL tool-call approvals for the authenticated user. */
    public function pending(): array
    {
        return $this->http->get('/api/v1/private/hitl/approvals/pending');
    }

    /**
     * List historical (decided) HITL approval records.
     *
     * @param array $params ['limit' => 50, 'offset' => 0]
     */
    public function history(array $params = []): array
    {
        return $this->http->get('/api/v1/private/hitl/approvals/history', $params);
    }

    /**
     * Approve a pending HITL tool-call approval.
     *
     * @param string $requestId The approval request ID
     * @param array  $params    Optional ['comment' => '...']
     */
    public function approve(string $requestId, array $params = []): array
    {
        return $this->http->post(
            '/api/v1/private/hitl/approvals/' . rawurlencode($requestId) . '/approve',
            $params ?: null
        );
    }

    /**
     * Reject a pending HITL tool-call approval.
     *
     * @param string $requestId The approval request ID
     * @param array  $params    Optional ['comment' => '...']
     */
    public function reject(string $requestId, array $params = []): array
    {
        return $this->http->post(
            '/api/v1/private/hitl/approvals/' . rawurlencode($requestId) . '/reject',
            $params ?: null
        );
    }

    /**
     * Bulk approve or reject multiple pending approvals.
     *
     * @param array $body ['requestIds' => ['r1', 'r2'], 'decision' => 'approved', 'comment' => '...']
     */
    public function bulkDecide(array $body): array
    {
        return $this->http->post('/api/v1/private/hitl/approvals/bulk', $body);
    }

    // ── Run-level inspection ─────────────────────────────────────────────────

    /** Get tool-call statistics for a specific pipeline run. */
    public function runToolStats(string $runId): array
    {
        return $this->http->get('/api/v1/private/hitl/runs/' . rawurlencode($runId) . '/tool-stats');
    }

    /** Get paginated messages for a pipeline run. */
    public function runMessages(string $runId, array $params = []): array
    {
        return $this->http->get(
            '/api/v1/private/hitl/runs/' . rawurlencode($runId) . '/messages',
            $params
        );
    }

    /** Get tool-call stats broken down by agent for a run. */
    public function runToolStatsByAgent(string $runId): array
    {
        return $this->http->get('/api/v1/private/hitl/runs/' . rawurlencode($runId) . '/tool-stats/by-agent');
    }

    /** Get all tool calls for a pipeline run. */
    public function runToolCalls(string $runId): array
    {
        return $this->http->get('/api/v1/private/hitl/runs/' . rawurlencode($runId) . '/tool-calls');
    }
}
