namespace Melaya;

/// <summary>
/// HITL (Human-in-the-Loop) API — list, approve, and reject pending tool-call
/// approvals generated by running pipelines.
/// Maps to <c>/api/v1/private/hitl/*</c>.
/// </summary>
/// <example>
/// <code>
/// var pending = await m.Hitl.PendingAsync();
/// foreach (var req in pending)
///     await m.Hitl.ApproveAsync(req.RequestId!, new HitlDecideRequest { Comment = "Looks good" });
/// </code>
/// </example>
public sealed class HitlApi
{
    private readonly MelayaHttpClient _http;

    internal HitlApi(MelayaHttpClient http) => _http = http;

    /// <summary>List all pending HITL tool-call approvals for the authenticated user.</summary>
    public async Task<List<HitlApproval>> PendingAsync(CancellationToken ct = default)
    {
        return await _http.GetAsync<List<HitlApproval>>("/api/v1/private/hitl/approvals/pending", ct: ct).ConfigureAwait(false);
    }

    /// <summary>List historical (decided) HITL approval records.</summary>
    public async Task<List<HitlApprovalHistory>> HistoryAsync(int? limit = null, int? offset = null, CancellationToken ct = default)
    {
        var q = Q(("limit", limit?.ToString()), ("offset", offset?.ToString()));
        return await _http.GetAsync<List<HitlApprovalHistory>>("/api/v1/private/hitl/approvals/history", q, ct).ConfigureAwait(false);
    }

    /// <summary>Approve a pending HITL tool-call approval.</summary>
    public async Task<BoolResult> ApproveAsync(string requestId, HitlDecideRequest? body = null, CancellationToken ct = default)
    {
        return await _http.PostAsync<BoolResult>(
            $"/api/v1/private/hitl/approvals/{Uri.EscapeDataString(requestId)}/approve",
            body, ct).ConfigureAwait(false);
    }

    /// <summary>Reject a pending HITL tool-call approval.</summary>
    public async Task<BoolResult> RejectAsync(string requestId, HitlDecideRequest? body = null, CancellationToken ct = default)
    {
        return await _http.PostAsync<BoolResult>(
            $"/api/v1/private/hitl/approvals/{Uri.EscapeDataString(requestId)}/reject",
            body, ct).ConfigureAwait(false);
    }

    /// <summary>Bulk approve or reject multiple pending approvals in one call.</summary>
    public async Task<HitlBulkDecideResult> BulkDecideAsync(HitlBulkDecideRequest body, CancellationToken ct = default)
    {
        return await _http.PostAsync<HitlBulkDecideResult>("/api/v1/private/hitl/approvals/bulk", body, ct).ConfigureAwait(false);
    }

    // ── Run-level inspection ──────────────────────────────────────────────────

    /// <summary>Get tool-call statistics for a specific pipeline run.</summary>
    public async Task<RunToolStats> RunToolStatsAsync(string runId, CancellationToken ct = default)
    {
        return await _http.GetAsync<RunToolStats>(
            $"/api/v1/private/hitl/runs/{Uri.EscapeDataString(runId)}/tool-stats", ct: ct).ConfigureAwait(false);
    }

    /// <summary>Get tool-call stats broken down by agent for a run.</summary>
    public async Task<System.Text.Json.JsonElement> RunToolStatsByAgentAsync(string runId, CancellationToken ct = default)
    {
        return await _http.GetAsync<System.Text.Json.JsonElement>(
            $"/api/v1/private/hitl/runs/{Uri.EscapeDataString(runId)}/tool-stats/by-agent", ct: ct).ConfigureAwait(false);
    }

    /// <summary>Get paginated messages for a pipeline run.</summary>
    public async Task<List<RunMessage>> RunMessagesAsync(string runId, int? limit = null, string? cursor = null, CancellationToken ct = default)
    {
        var q = Q(("limit", limit?.ToString()), ("cursor", cursor));
        return await _http.GetAsync<List<RunMessage>>(
            $"/api/v1/private/hitl/runs/{Uri.EscapeDataString(runId)}/messages", q, ct).ConfigureAwait(false);
    }

    /// <summary>Get all tool calls for a pipeline run.</summary>
    public async Task<List<RunToolCall>> RunToolCallsAsync(string runId, CancellationToken ct = default)
    {
        return await _http.GetAsync<List<RunToolCall>>(
            $"/api/v1/private/hitl/runs/{Uri.EscapeDataString(runId)}/tool-calls", ct: ct).ConfigureAwait(false);
    }

    private static Dictionary<string, string?> Q(params (string Key, string? Value)[] pairs)
    {
        var d = new Dictionary<string, string?>(pairs.Length);
        foreach (var (k, v) in pairs)
            if (v is not null) d[k] = v;
        return d;
    }
}
