package org.melaya;

import com.fasterxml.jackson.databind.JsonNode;

import java.util.Map;

import static org.melaya.MarketAPI.params;

/**
 * HITL (Human-in-the-Loop) API — list, approve, and reject pending tool-call
 * approvals generated by running pipelines.
 *
 * <p>Maps to {@code /api/v1/private/hitl/*}.
 *
 * @example
 * <pre>{@code
 * JsonNode pending = melaya.hitl().pending();
 * for (JsonNode req : pending) {
 *     melaya.hitl().approve(req.get("requestId").asText(), null);
 * }
 * }</pre>
 */
public class HitlAPI {

    private final HttpClient http;

    HitlAPI(HttpClient http) {
        this.http = http;
    }

    /** List all pending HITL tool-call approvals for the authenticated user. */
    public JsonNode pending() {
        return http.get("/api/v1/private/hitl/approvals/pending", null);
    }

    /**
     * List historical (decided) HITL approval records.
     *
     * @param limit  optional page size; may be {@code null}
     * @param offset optional page offset; may be {@code null}
     */
    public JsonNode history(Integer limit, Integer offset) {
        Map<String, Object> q = params("limit", limit, "offset", offset);
        return http.get("/api/v1/private/hitl/approvals/history", q.isEmpty() ? null : q);
    }

    /**
     * Approve a pending HITL tool-call approval.
     *
     * @param requestId the approval request ID
     * @param body      optional map; may contain {@code comment}
     */
    public JsonNode approve(String requestId, Map<String, Object> body) {
        return http.post(
                "/api/v1/private/hitl/approvals/" + encode(requestId) + "/approve",
                body);
    }

    /**
     * Reject a pending HITL tool-call approval.
     *
     * @param requestId the approval request ID
     * @param body      optional map; may contain {@code comment}
     */
    public JsonNode reject(String requestId, Map<String, Object> body) {
        return http.post(
                "/api/v1/private/hitl/approvals/" + encode(requestId) + "/reject",
                body);
    }

    /**
     * Bulk approve or reject multiple pending approvals in one call.
     *
     * @param body map containing {@code requestIds} (List&lt;String&gt;),
     *             {@code decision} ({@code "approved"} or {@code "rejected"}),
     *             and optional {@code comment}
     */
    public JsonNode bulkDecide(Map<String, Object> body) {
        return http.post("/api/v1/private/hitl/approvals/bulk", body);
    }

    // ── Run-level inspection ──────────────────────────────────────────────────

    /**
     * Get tool-call statistics for a specific pipeline run.
     *
     * @param runId the pipeline run ID
     */
    public JsonNode runToolStats(String runId) {
        return http.get("/api/v1/private/hitl/runs/" + encode(runId) + "/tool-stats", null);
    }

    /**
     * Get paginated messages for a pipeline run.
     *
     * @param runId  the pipeline run ID
     * @param limit  optional page size; may be {@code null}
     * @param cursor optional pagination cursor; may be {@code null}
     */
    public JsonNode runMessages(String runId, Integer limit, String cursor) {
        Map<String, Object> q = params("limit", limit, "cursor", cursor);
        return http.get("/api/v1/private/hitl/runs/" + encode(runId) + "/messages",
                q.isEmpty() ? null : q);
    }

    /**
     * Get tool-call stats broken down by agent for a run.
     *
     * @param runId the pipeline run ID
     */
    public JsonNode runToolStatsByAgent(String runId) {
        return http.get(
                "/api/v1/private/hitl/runs/" + encode(runId) + "/tool-stats/by-agent",
                null);
    }

    /**
     * Get all tool calls for a pipeline run.
     *
     * @param runId the pipeline run ID
     */
    public JsonNode runToolCalls(String runId) {
        return http.get("/api/v1/private/hitl/runs/" + encode(runId) + "/tool-calls", null);
    }

    // ── helpers ───────────────────────────────────────────────────────────────

    private static String encode(String s) {
        try {
            return java.net.URLEncoder.encode(s, java.nio.charset.StandardCharsets.UTF_8);
        } catch (Exception e) {
            return s;
        }
    }
}
